@echo off
Del DOS4GW.Exe
echo ÿFANTASY EMPIRES(TM) Patch Disk v1.1: December 19, 1993.
echo ÿ
echo ÿThere are 2 bugs that have been fixed and several others that may have 
echo ÿbeen as well due to the use of DOS4GPRO.
echo ÿ
echo ÿDefinite fixes:
echo ÿ
echo ÿMultiplying Siege Engine Bug:  This bug occurred only when the detail 
echo ÿlevel was not set to 1:1.  It is now fixed.
echo ÿ
echo ÿDisappearing Hero Bug:  If a defending player hit 'escape' to simulate 
echo ÿthe battle and had heroes in the country, the heroes would disappear.  
echo ÿThis bug has now been fixed.
echo ÿ
echo ÿOthers:
echo ÿ
echo ÿFantasy Empires now uses DOS4GPRO and no longer uses the program 
echo ÿdos4gw.exe.  This change should eliminate some hardware incompatibil-
echo ÿities.  This will also free up more RAM so memory will not be as 
echo ÿtight as before.
echo ÿ
echo ÿIMPORTANT NOTE:
echo ÿ
pause
echo ÿFor those who are using emm386.exe with dos6.0.  Our program uses 
echo ÿextended memory only and does not require emm386.  If you are having 
echo ÿproblems, remove it from your system configuration.  We have also 
echo ÿpulled some text provided with dos4gwpro that addresses problems with 
echo ÿemm386.
echo ÿ
echo ÿ*9b. EMM386.EXE provided with DOS 6.0.
echo ÿ*
echo ÿ*        We know of at least two serious bugs in the EMM386.EXE
echo ÿ*        distributed with MS-DOS 6.0, one involving mis-counting the
echo ÿ*        amount of available memory, and one involving mapping too
echo ÿ*        little of the High Memory Area (HMA) into its page tables.
echo ÿ*
echo ÿ*        If you are having problems with DOS/4GW Professional and you
echo ÿ*        are using an EMM386.EXE dated 3-10-93 at 6:00:00, or later,
echo ÿ*        you may wish to consider one of the following workarounds.
echo ÿ*
echo ÿ*        * Replace EMM386 with another memory manager, such as
echo ÿ*          QEMM-386, 386Max, or an older version of EMM386
echo ÿ*        * Run in a Windows DOS box
echo ÿ*        * Run with HIMEM.SYS alone
echo ÿ*        * Convert the DEVICEHIGH statements in your CONFIG.SYS
echo ÿ*          to DEVICE statements, and remove the LH (Load High)
pause
echo ÿ*          commands from your AUTOEXEC.BAT.
echo ÿ*
echo ÿ*        You may also wish to contact Microsoft Corporation to inquire
echo ÿ*        about the availability of a fix.
echo ÿ*
echo ÿTaken from Rational Systems Read.me file.
echo ÿ
echo ÿ
echo ÿWe hope that you enjoy Fantasy Empires.
echo ÿ
echo ÿDenis Dyack.
echo ÿSilicon Knights.
echo ÿÿÿ
